{% set name = "efficientnet-pytorch" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/efficientnet_pytorch-{{ version }}.tar.gz
  sha256: 7c0093428fc6a4137465de0f8101332a31c98072200ac8e14a6324cedad3b109

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python
    - pytorch >=3.6

test:
  imports:
    - efficientnet_pytorch

about:
  home: https://github.com/lukemelas/efficientnet_pytorch
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: EfficientNet implemented in PyTorch.
  dev_url: https://github.com/lukemelas/efficientnet_pytorch

extra:
  recipe-maintainers:
    - mxr-conda
    - oblute
    - rluria14
    - ndmaxar
